### ISSUE TITLE
i have run this app it can generate error. 

### ISSUE THREAD

**Issue by cooldeeparmar** [valnub/Framework7-with-AngularJS-demo-app#4]
@@include('html/header.html')
@@include('html/navi.html')
@@include('html/pages/indexpage.html')
@@include('html/pages/detailspage.html')

**Comment by valnub** [comment]
Please read the manual https://github.com/valnub/Framework7-with-AngularJS-demo-app#how-to-build

You have to run the right build target and then deploy the result of the build on your webserver.
